export const data = [
    {
        id: 1,
        title: 'Стул из массива',
        img: 'catalog1.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'chairs',
        price: '20.99',
    },
    {
        id: 2,
        title: 'Стол из массива',
        img: 'catalog2.jpeg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'table',
        price: '55.99',
    },
    {
        id: 3,
        title: 'Стул из массива',
        img: 'catalog3.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'chairs',
        price: '10.99',
    },
    {
        id: 4,
        title: 'Стол из массива',
        img: 'catalog4.jpeg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'table',
        price: '50.99',
    },
    {
        id: 5,
        title: 'Торшер',
        img: 'catalog5.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'light',
        price: '23.99',
    },
    {
        id: 6,
        title: 'Люстра',
        img: 'catalog6.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'light',
        price: '30.99',
    },
    {
        id: 7,
        title: 'Диван велюр',
        img: 'catalog7.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'sofa',
        price: '99.99',
    },
    {
        id: 8,
        title: 'Диван круглый',
        img: 'catalog8.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'sofa',
        price: '78.99',
    },
    {
        id: 9,
        title: 'Диван футер',
        img: 'catalog9.jpeg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'sofa',
        price: '149.99',
    },
    {
        id: 10,
        title: 'Стул из овчины',
        img: 'catalog10.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'chairs',
        price: '10.99',
    },
    {
        id: 11,
        title: 'Стол',
        img: 'catalog11.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'table',
        price: '50.99',
    },
    {
        id: 12,
        title: 'Люстра',
        img: 'catalog12.jpg',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
        category: 'light',
        price: '30.99',
    },
];
